version: '3.8'
services:
  aspnet-db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306:3306'
    volumes:
      - aspnet-db:/var/lib/mysql
      - ./aspnet-db/init.sql:/docker-entrypoint-initaspnet-db.d/init.sql
volumes:
  aspnet-db:
    driver: local
