name: Desafios

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      working-directory: ./desafios
      run: dotnet restore
    - name: Build
      working-directory: ./desafios
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./desafios
      run: dotnet test --no-build --verbosity normal
